import { Team } from './types';

const teams: Team[] = [
  {
    id: 1,
    name: 'Atlanta Hawks',
    nickname: 'Hawks',
    code: 'ATL',
    city: 'Atlanta',
    logo: 'https://cdn.nba.com/logos/nba/1610612737/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Southeast' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Southeast' },
      sacramento: { conference: 'East', division: 'Southeast' },
    },
  },
  {
    id: 2,
    name: 'Boston Celtics',
    nickname: 'Celtics',
    code: 'BOS',
    city: 'Boston',
    logo: 'https://cdn.nba.com/logos/nba/1610612738/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Atlantic' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Atlantic' },
      sacramento: { conference: 'East', division: 'Atlantic' },
    },
  },
  {
    id: 4,
    name: 'Brooklyn Nets',
    nickname: 'Nets',
    code: 'BKN',
    city: 'Brooklyn',
    logo: 'https://cdn.nba.com/logos/nba/1610612751/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Atlantic' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Atlantic' },
      sacramento: { conference: 'East', division: 'Atlantic' },
    },
  },
  {
    id: 5,
    name: 'Charlotte Hornets',
    nickname: 'Hornets',
    code: 'CHA',
    city: 'Charlotte',
    logo: 'https://cdn.nba.com/logos/nba/1610612766/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Southeast' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Southeast' },
      sacramento: { conference: 'East', division: 'Southeast' },
    },
  },
  {
    id: 6,
    name: 'Chicago Bulls',
    nickname: 'Bulls',
    code: 'CHI',
    city: 'Chicago',
    logo: 'https://cdn.nba.com/logos/nba/1610612741/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Central' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Central' },
      sacramento: { conference: 'East', division: 'Central' },
    },
  },
  {
    id: 7,
    name: 'Cleveland Cavaliers',
    nickname: 'Cavaliers',
    code: 'CLE',
    city: 'Cleveland',
    logo: 'https://cdn.nba.com/logos/nba/1610612739/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Central' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Central' },
      sacramento: { conference: 'East', division: 'Central' },
    },
  },
  {
    id: 8,
    name: 'Dallas Mavericks',
    nickname: 'Mavericks',
    code: 'DAL',
    city: 'Dallas',
    logo: 'https://cdn.nba.com/logos/nba/1610612742/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Southwest' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Southwest' },
      sacramento: { conference: 'West', division: 'Southwest' },
    },
  },
  {
    id: 9,
    name: 'Denver Nuggets',
    nickname: 'Nuggets',
    code: 'DEN',
    city: 'Denver',
    logo: 'https://cdn.nba.com/logos/nba/1610612743/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Northwest' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Northwest' },
      sacramento: { conference: 'West', division: 'Northwest' },
    },
  },
  {
    id: 10,
    name: 'Detroit Pistons',
    nickname: 'Pistons',
    code: 'DET',
    city: 'Detroit',
    logo: 'https://cdn.nba.com/logos/nba/1610612765/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Central' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Central' },
      sacramento: { conference: 'East', division: 'Central' },
    },
  },
  {
    id: 11,
    name: 'Golden State Warriors',
    nickname: 'Warriors',
    code: 'GSW',
    city: 'Golden State',
    logo: 'https://cdn.nba.com/logos/nba/1610612744/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Pacific' },
      sacramento: { conference: 'California', division: null },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Pacific' },
    },
  },
  {
    id: 14,
    name: 'Houston Rockets',
    nickname: 'Rockets',
    code: 'HOU',
    city: 'Houston',
    logo: 'https://cdn.nba.com/logos/nba/1610612745/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Southwest' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Southwest' },
      sacramento: { conference: 'West', division: 'Southwest' },
    },
  },
  {
    id: 15,
    name: 'Indiana Pacers',
    nickname: 'Pacers',
    code: 'IND',
    city: 'Indiana',
    logo: 'https://cdn.nba.com/logos/nba/1610612754/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Central' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Central' },
      sacramento: { conference: 'East', division: 'Central' },
    },
  },
  {
    id: 16,
    name: 'LA Clippers',
    nickname: 'Clippers',
    code: 'LAC',
    city: 'LA',
    logo: 'https://cdn.nba.com/logos/nba/1610612746/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Pacific' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Pacific' },
      sacramento: { conference: 'West', division: 'Pacific' },
    },
  },
  {
    id: 17,
    name: 'Los Angeles Lakers',
    nickname: 'Lakers',
    code: 'LAL',
    city: 'Los Angeles',
    logo: 'https://cdn.nba.com/logos/nba/1610612747/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Pacific' },
      sacramento: { conference: 'California', division: null },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Pacific' },
    },
  },
  {
    id: 19,
    name: 'Memphis Grizzlies',
    nickname: 'Grizzlies',
    code: 'MEM',
    city: 'Memphis',
    logo: 'https://cdn.nba.com/logos/nba/1610612763/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Southwest' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'Utah', division: null },
      sacramento: { conference: 'West', division: 'Southwest' },
    },
  },
  {
    id: 20,
    name: 'Miami Heat',
    nickname: 'Heat',
    code: 'MIA',
    city: 'Miami',
    logo: 'https://cdn.nba.com/logos/nba/1610612748/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Southeast' },
      sacramento: { conference: 'California', division: null },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Southeast' },
    },
  },
  {
    id: 21,
    name: 'Milwaukee Bucks',
    nickname: 'Bucks',
    code: 'MIL',
    city: 'Milwaukee',
    logo: 'https://cdn.nba.com/logos/nba/1610612749/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Central' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Central' },
      sacramento: { conference: 'East', division: 'Central' },
    },
  },
  {
    id: 22,
    name: 'Minnesota Timberwolves',
    nickname: 'Timberwolves',
    code: 'MIN',
    city: 'Minnesota',
    logo: 'https://cdn.nba.com/logos/nba/1610612750/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Northwest' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Northwest' },
      sacramento: { conference: 'West', division: 'Northwest' },
    },
  },
  {
    id: 23,
    name: 'New Orleans Pelicans',
    nickname: 'Pelicans',
    code: 'NOP',
    city: 'New Orleans',
    logo: 'https://cdn.nba.com/logos/nba/1610612740/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Southwest' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Southwest' },
      sacramento: { conference: 'West', division: 'Southwest' },
    },
  },
  {
    id: 24,
    name: 'New York Knicks',
    nickname: 'Knicks',
    code: 'NYK',
    city: 'New York',
    logo: 'https://cdn.nba.com/logos/nba/1610612752/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Atlantic' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Atlantic' },
      sacramento: { conference: 'East', division: 'Atlantic' },
    },
  },
  {
    id: 25,
    name: 'Oklahoma City Thunder',
    nickname: 'Thunder',
    code: 'OKC',
    city: 'Oklahoma City',
    logo: 'https://cdn.nba.com/logos/nba/1610612760/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Northwest' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'Utah', division: null },
      sacramento: { conference: 'West', division: 'Northwest' },
    },
  },
  {
    id: 26,
    name: 'Orlando Magic',
    nickname: 'Magic',
    code: 'ORL',
    city: 'Orlando',
    logo: 'https://cdn.nba.com/logos/nba/1610612753/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Southeast' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Southeast' },
      sacramento: { conference: 'East', division: 'Southeast' },
    },
  },
  {
    id: 27,
    name: 'Philadelphia 76ers',
    nickname: '76ers',
    code: 'PHI',
    city: 'Philadelphia',
    logo: 'https://cdn.nba.com/logos/nba/1610612755/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Atlantic' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'Utah', division: null },
      sacramento: { conference: 'East', division: 'Atlantic' },
    },
  },
  {
    id: 28,
    name: 'Phoenix Suns',
    nickname: 'Suns',
    code: 'PHX',
    city: 'Phoenix',
    logo: 'https://cdn.nba.com/logos/nba/1610612756/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Pacific' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Pacific' },
      sacramento: { conference: 'West', division: 'Pacific' },
    },
  },
  {
    id: 29,
    name: 'Portland Trail Blazers',
    nickname: 'Trail Blazers',
    code: 'POR',
    city: 'Portland',
    logo: 'https://cdn.nba.com/logos/nba/1610612757/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Northwest' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Northwest' },
      sacramento: { conference: 'West', division: 'Northwest' },
    },
  },
  {
    id: 30,
    name: 'Sacramento Kings',
    nickname: 'Kings',
    code: 'SAC',
    city: 'Sacramento',
    logo: 'https://cdn.nba.com/logos/nba/1610612758/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Pacific' },
      sacramento: { conference: 'California', division: null },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Pacific' },
    },
  },
  {
    id: 31,
    name: 'San Antonio Spurs',
    nickname: 'Spurs',
    code: 'SAS',
    city: 'San Antonio',
    logo: 'https://cdn.nba.com/logos/nba/1610612759/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Southwest' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'West', division: 'Southwest' },
      sacramento: { conference: 'West', division: 'Southwest' },
    },
  },
  {
    id: 38,
    name: 'Toronto Raptors',
    nickname: 'Raptors',
    code: 'TOR',
    city: 'Toronto',
    logo: 'https://cdn.nba.com/logos/nba/1610612761/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Atlantic' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Atlantic' },
      sacramento: { conference: 'East', division: 'Atlantic' },
    },
  },
  {
    id: 40,
    name: 'Utah Jazz',
    nickname: 'Jazz',
    code: 'UTA',
    city: 'Utah',
    logo: 'https://cdn.nba.com/logos/nba/1610612762/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'West', division: 'Northwest' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'Utah', division: null },
      sacramento: { conference: 'West', division: 'Northwest' },
    },
  },
  {
    id: 41,
    name: 'Washington Wizards',
    nickname: 'Wizards',
    code: 'WAS',
    city: 'Washington',
    logo: 'https://cdn.nba.com/logos/nba/1610612764/global/L/logo.svg',
    allStar: false,
    nbaFranchise: true,
    leagues: {
      standard: { conference: 'East', division: 'Southeast' },
      vegas: { conference: 'summer', division: null },
      utah: { conference: 'East', division: 'Southeast' },
      sacramento: { conference: 'East', division: 'Southeast' },
    },
  },
];

export default teams;
